#!/usr/bin/python
#
# -*- coding: utf-8 -*-
# Simple commandlinetool to generate code for code generators
#

import sys

#
# Constants
#
PS_INTEXT = 0
PS_INBRACKETS = 1
PS_INVALUEASSIGNMENT = 2
PS_INCODE = 3

ENC_HTML = "html"
ENC_C = "c"


#
# Function for reading the template file
#
def read_file(filename):
    f = open(filename, 'r')
    string = f.read()
    return string


#
# Converts the given String into a push statement
#
def to_push(string, encodetype):
    if encodetype == "c":
        val = string.replace("\\", "\\\\").replace("\n", "\\n").replace("\t", "\\t").replace("\"", "\\\"")
        return "str.push_str(\"{0}\");".format(val);
    elif encodetype == "html":
        val = string.replace("<", "&lt;").replace(">", "&gt;").replace("\n", "<br>")
        return "str.push_str(\"{0}\");".format(val);


#
# Converts the given String into a formated push statement
#
def to_assignment(string):
    val = string.strip(' ')
    return "str.push_str(&{0});".format(val)
    #return "write!(&mut str, \"{1}\", {0});".format(val, "{}")


#
# Parser-Function
#
def parse(filename, encodetype):
    code = read_file(filename)
    state = PS_INTEXT
    buffer = ""
    charbefore = ' '

    for c in code:
        if state == PS_INTEXT:
            if c == '{' and charbefore == '{':
                state = PS_INBRACKETS
                if buffer.__len__() > 1:
                    print to_push(buffer[0:buffer.__len__()-2], encodetype)
                buffer = ""
            else:
                buffer += c
        elif state == PS_INBRACKETS:
            if c == '=':
                state = PS_INVALUEASSIGNMENT
            elif c == ' ':
                state = PS_INCODE
            else:
                print "Error: invalid char {0}".format(c)
        elif state == PS_INCODE:
            if c == '}' and charbefore == '}':
                state = PS_INTEXT
                print buffer[0:buffer.__len__()-1]
                buffer = ""
            else:
                buffer += c
        elif state == PS_INVALUEASSIGNMENT:
            if c == '}' and charbefore == '}':
                state = PS_INTEXT
                print to_assignment(buffer[0:buffer.__len__()-1])
                buffer = ""
            else:
                buffer += c

        charbefore = c

    if state == PS_INTEXT and buffer.__len__() > 1:
        print to_push(buffer, encodetype)


#
# Main
#
if sys.argv.__len__() == 3:
    parse(sys.argv[1], sys.argv[2])
else:
    print "Usage: generate_code filename [c|html]"
